\label{chap:parameters}
\starredchapter{APPENDIX~\thechapter. PARAMETERS ESTIMATED INDEPENDENTLY}
\lfoot{\fishName}
\rfoot{Appendix~\thechapter~-- Parameters}

Here we discuss parameters estimated outside the model:

\begin{resdoclist}
\item Growth rates
\item Natural mortality
\item Maturity-at-age?
\item Other?
\end{resdoclist}

\appsection{GROWTH RATES}

Interesting facts about growth.

% Dirty hack to maintain correct appendix letters
\newpage